[parity]
chain = "/dev-chain/spec.json"

[footprint]
pruning = "archive"

[mining]
reseal_min_period = 0
min_gas_price = 0

[rpc]
interface = "all"
apis = ["all"]
hosts = ["all"]
cors = ["all"]

[websockets]
interface = "all"
hosts = ["all"]
origins = ["all"]
